#ifndef __MAG_PROJECT_CONSTANTS_H__
#define __MAG_PROJECT_CONSTANTS_H__

#define MASTER_WIDTH			700
#define MASTER_HEIGHT			630

#define IDC_SEND_BUTTON		101
#define IDC_URL_ENTRY			102

#define IDC_RADIO_GET			201
#define IDC_RADIO_POST		202
#define IDC_RADIO_PUT			203
#define IDC_RADIO_PATCH		204
#define IDC_RADIO_DELETE	205
#define IDC_RADIO_HEAD		206
#define	IDC_RADIO_OPTIONS	207

#define IDC_RESPONSE_AREA 301

#define SET_RESPONSE_TEXT	0xABCD

#define RADIO_BTN_HEIGHT	30
#define RADIO_BTN_WIDTH		100

enum ThreadStatuses {
	THREAD_STATUS_CONNECTING,
	THREAD_STATUS_WAITING,
	THREAD_STATUS_RECEIVING_RESPONSE,
	THREAD_STATUS_DONE,
	THREAD_STATUS_TOTAL
};

enum ControlIDs {
	BTN_SEND, 
	URL_ENTRY,
	OPT_GET,
	OPT_POST,
	OPT_PUT,
	OPT_PATCH,
	OPT_DELETE,
	OPT_HEAD,
	OPT_OPTIONS,
	AREA_RESPONSE,
	CONTROL_ID_TOTAL
};

enum OptionIDs {
	OPTION_METHOD,
	OPTION_PATH,
	OPTION_TOTAL
};

#endif